---
# ntp install
- name: Install chrony for NTP
  yum: name={{ item }} state=latest
  with_items:
    - chrony

- name: Deploy chrony configuration files from templates
  template: src={{ item.src }} dest={{ item.dest }}  backup=yes
  with_items:
    - { src: 'chrony.conf.j2', dest: '/etc/chrony.conf' }

- name: Restart services
  service: name={{ item }} enabled=yes state=started
  with_items:
    - chronyd