---
# tasks file for firewall

- name: Configure firewall.
  template: src={{ item.src }} dest={{ item.dest }} backup=yes
  with_items:
    - { src: 'iptables.j2', dest: '/etc/sysconfig/iptables' }

- name: Restart iptables.
  service: name=iptables state=restarted