---
# tasks file for glance

# Prerequisites
- name: Prepare Database for glance.
  include: database.yml
  vars:
    db_name: "{{ openstack_glance_db_name }}"
    db_user: "{{ openstack_glance_db_user }}"
    db_password: "{{ openstack_glance_db_password }}"
    db_priv: "{{ openstack_glance_db_name }}.*:ALL"
  tags: database

- name: "Create glance user in service project"
  include: openstack/create_user_in_project.yml
  vars:
    username: glance
    password: "{{ openstack_glance_keystone_password }}"
    role: admin
    project: service

- name: Create the service entity for glance.
  include: openstack/create_service.yml
  vars:
    name: glance
    type: image
    description: OpenStack Image service

- name: Create the API endpoint for glance.
  include: openstack/create_endpoint.yml
  vars:
    service: image
    region: RegionOne
    endpoints:
      adminurl: "{{ openstack_glance_adminurl }}"
      internalurl: "{{ openstack_glance_internalurl }}"
      publicurl: "{{ openstack_glance_publicurl }}"

# Install and configure
- name: Install OpenStack glance packages.
  yum: name={{ item }} state=installed
  with_items:
    - openstack-glance
    - python-glance
    - python-glanceclient

- name: Deploy glance configuration files from templates
  template: src={{ item.src }} dest={{ item.dest }} backup=yes
  with_items:
    - { src: 'glance/glance-api.conf.j2', dest: '/etc/glance/glance-api.conf' }
    - { src: 'glance/glance-registry.conf.j2', dest: '/etc/glance/glance-registry.conf'}
    - { src: 'glance/glance-api-paste.ini.j2', dest: '/etc/glance/glance-api-paste.ini' }
    - { src: 'glance/glance-registry-paste.ini.j2', dest: '/etc/glance/glance-registry-paste.ini' }
#    - { src: 'glance/policy.json.j2', dest: '/etc/glance/policy.json' }  TODO(jorgesece): check it
  notify: restart glance-registry

- name: Give permissions to /var/log/glance/api.log
  file: path=/var/log/glance/api.log state=touch mode=0640 owner=glance group=apache

- name:  Create keystone tables in DB
  shell: glance-manage db_sync
  become_user: glance
  run_once: True

- name: Ensure images service is started and enabled on boot
  service: name={{ item }} enabled=yes state=started
  with_items:
  - openstack-glance-api
  - openstack-glance-registry
