---
# tasks file for horizon

- name: Install OpenStack horizon packages.
  package: name={{ item }} state=latest
  with_items:
    - openstack-dashboard

- name: Copy file openstack-dashbard.conf
  file: src=openstack-dashboard.conf dest=/etc/httpd/conf.d/openstack-dashboard.conf

- name: Set ServerName
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: "^ServerName "
    insertafter: "^#ServerName "
    line: "ServerName {{ ansible_default_ipv4.address }}"

- name: Copy the configuration files for horizon.
  template: src=horizon/horizon_local_settings-u18.j2 dest=/etc/openstack-dashboard/local_settings.py
  notify: restart horizon
  when: ansible_os_family == 'Debian'

- name: Copy the configuration files for horizon.
  template: src=horizon/horizon_local_settings-c7.j2 dest=/etc/openstack-dashboard/local_settings
  notify: restart horizon
  when: ansible_os_family == 'RedHat'
