---
# tasks file for horizon

- name: Install OpenStack horizon packages.
  apt: name={{ item }} state=latest
  with_items:
    - openstack-dashboard

- name: Copy the configuration files for horizon.
  template: src=horizon/horizon_local_settings.j2 dest=/etc/openstack-dashboard/local_settings.py
  notify: restart horizon
