---
# Configure the host name and add the ip to the /etc/hosts

#SELINUX
- name: Set Selinux in permissive mode
  shell: setenforce 0

- name: Persist in the configuration file the Selinux permissive mode.
  lineinfile: >
    dest=/etc/sysconfig/selinux
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
  with_items:
    - { regexp: "^SELINUX=", line: "SELINUX=disable" }

#Host name
- name: Set hostame to "{{ openstack_controller_host }}"
  shell: hostnamectl set-hostname "{{ openstack_controller_host }}"
  ignore_errors: True

- name: Test {{ openstack_controller_ip }} exist
  shell: grep "^{{ openstack_controller_ip }}" /etc/hosts
  register: test_exits

- name: Add "{{ openstack_controller_host }}" to hosts file
  when: test_grep.stdout != ""
  lineinfile: dest=/etc/ansible/roles/ansible-role-os-controller/tests/hosts_docker
              backup=True
              backrefs=True
              state=present
              regexp='(^127.0.0.1(\s+(?! {{ openstack_controller_host }})[\w=/\-\.]+)*)\s*$'
              line='\1 {{ openstack_controller_host }}'

- name: Add "{{ openstack_controller_ip }}" to hosts file
  when: test_grep.stdout == ""
  lineinfile: dest=/etc/hosts line="{{ openstack_controller_ip }} {{ openstack_controller_host }}"