---
# Configure the host name and add the ip to the /etc/hosts

#Host name
- name: Set hostame to "{{ openstack_controller_host }}"
  shell: hostnamectl set-hostname {{ openstack_controller_host }}
  ignore_errors: True

- name: "Test {{ openstack_controller_ip }} exists in /etc/hosts"
  shell: grep "^{{ openstack_controller_ip }}" /etc/hosts
  register: ip_exits
  ignore_errors: True

- name: "Test {{ openstack_controller_host }} exists in /etc/hosts"
  shell: grep "{{ openstack_controller_host }}" /etc/hosts
  register: host_exits
  ignore_errors: True

- name: Add "{{ openstack_controller_host }}" to hosts file if ip exists
  when: ip_exits.stdout != "" and host_exits.stdout == ""
  lineinfile: dest=/etc/hosts
              backup=True
              backrefs=True
              state=present
              regexp='(^{{ openstack_controller_ip }}(\s+(?! {{ openstack_controller_host }})[\w=/\-\.]+)*)\s*$'
              line='\1 {{ openstack_controller_host }}'

- name: Add "{{ openstack_controller_ip }}" to hosts file if ip does not exist
  when: ip_exits.stdout == "" and host_exits.stdout == ""
  shell: echo "{{ openstack_controller_ip }} {{ openstack_controller_host }}" >> /etc/hosts