---
- name: Install packages keystone and mod-wsgi
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - keystone
    - libapache2-mod-wsgi
    - python-openstackclient

- name: Install cjose and mod_auth_openidc
  apt: deb={{ item }}
  with_items:
    - '{{ url_cjose }}'
    - '{{ url_oidc }}'

- name: Deploy keyston configuration files from templates
  template: src={{ item.src }} dest={{ item.dest }} mode=0644
  with_items:
    - { src: 'keystone/keystone.conf.j2', dest: '/etc/keystone/keystone.conf' }
    - { src: 'keystone/wsgi-keystone.conf.j2', dest: '/etc/apache2/sites-available/keystone.conf' }

- name: Restart apache
  service: name=apache2 enabled=yes state=restarted

- name: Waiting for keystone service is started.
  wait_for: "host={{ openstack_controller_host }} port=35357 timeout=10"
  run_once: true

- name: Create keystone tables in DB
  command: keystone-manage db_sync
  become: true
  become_user: keystone
  run_once: true

- name: Initialize fernet tokens
  command: keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone
  run_once: true

- name: Initialize fernet tokens
  command: keystone-manage credential_setup --keystone-user keystone --keystone-group keystone
  run_once: true
  notify: restart apache

- name: Bootstrap keystone admin and endpoint
  command: |
     keystone-manage bootstrap \
     --bootstrap-password {{ openstack_admin_password }} \
     --bootstrap-region-id {{ openstack_keystone_auth_region }} \
     --bootstrap-admin-url {{ openstack_endpoint_admin_url }} \
     --bootstrap-public-url {{ openstack_endpoint_public_url }} \
     --bootstrap-internal-url {{ openstack_endpoint_internal_url }}
  register: add_service
  until: add_service|success
  retries: 3
  delay: 5

# Project service
- name: "Create the service project"
  include: openstack/create_project.yml
  vars:
    project: service
    description: "Service project"
