---
# tasks file for keystone

# Prerequisites
- name: Prepare Database for keystone.
  include: database.yml
  vars:
    db_name: "{{ openstack_keystone_db_name }}"
    db_user: "{{ openstack_keystone_db_user }}"
    db_password: "{{ openstack_keystone_db_password }}"
    db_priv: "{{ openstack_keystone_db_name }}.*:ALL"
  tags: database

- name: Install OpenStack keystone package.
  yum: name={{ item }} state=latest
  with_items:
    - openstack-keystone
  retries: 2
  delay: 5

#http

- name: Configure httpd Listen Port.
  lineinfile: >
    dest=/etc/httpd/conf/httpd.conf
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
  with_items:
    - { regexp: "^#?Listen", line: "Listen {{ openstack_http_port }}" }
    - { regexp: "^#?ServerName", line: "ServerName {{ openstack_controller_host }}" }

- name: Deploy keyston configuration files from templates
  template: src={{ item.src }} dest={{ item.dest }} mode=0640 owner=keystone group=apache backup=yes
  with_items:
    - { src: 'keystone/keystone-dist-paste.ini.j2', dest: '/etc/keystone/keystone-dist-paste.ini' }
    - { src: 'keystone/keystone.conf.j2', dest: '/etc/keystone/keystone.conf' }
    - { src: 'keystone/wsgi-keystone.conf.j2', dest: '/etc/httpd/conf.d/wsgi-keystone.conf' }

- name: Start http daemon.
  service: "name={{ item }} enabled=yes state=restarted"
  with_items:
    - httpd

#rabbit
- name: Service rabbitmq
  service: name=rabbitmq-server enabled=yes state=restarted

- name: rabbitmq user setup
  rabbitmq_user: user={{ openstack_rabbit_user }}
                 password={{ openstack_rabbit_pass }}
                 vhost=/
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present

- name: Waiting for keystone service is started.
  wait_for: "host={{ openstack_controller_host }} port=35357 delay=10 timeout=30"
  run_once: true

- name: Give permissions to keystone.log
  file: path=/var/log/keystone/keystone.log state=touch mode=0640 owner=keystone group=apache

- name:  Create keystone tables in DB
  shell: keystone-manage db_sync
  become_user: keystone
  run_once: True

- name: Create the service entity for keystone.
  include: openstack/create_service.yml
  vars:
    name: keystone
    type: identity
    description: OpenStack Identity

- name: Create the API endpoint for keystone.
  include: openstack/create_endpoint.yml
  vars:
    service: identity
    region: RegionOne
    endpoints:
      adminurl: "{{ openstack_endpoint_admin_url }}"
      internalurl: "{{ openstack_endpoint_internal_url }}"
      publicurl: "{{ openstack_endpoint_public_url }}"

# admin
- name: "Create admin project"
  include: openstack/create_project.yml
  vars:
    project: admin
    description: "Admin project"

- name: "Create admin role"
  include: openstack/create_role.yml
  vars:
    role: admin

- name: "Create admin user in admin project"
  include: openstack/create_user_in_project.yml
  vars:
    username: admin
    password: "{{ openstack_admin_password }}"
    project: admin
    role: admin

# user
- name: "Create demo project"
  include: openstack/create_project.yml
  vars:
    project: "{{ openstack_user_project }}"
    description: "Demo project"

- name: "Create demo role"
  include: openstack/create_role.yml
  vars:
    role: "{{ openstack_user_role }}"

- name: "Create demo user in demo project"
  include: openstack/create_user_in_project.yml
  vars:
    username: "{{ openstack_user_name }}"
    password: "{{ openstack_user_password }}"
    project: "{{ openstack_user_project }}"
    role: "{{ openstack_user_role }}"

#service
- name: "Create the service project"
  include: openstack/create_project.yml
  vars:
    project: service
    description: "Service project"