---
- name: Configure open file limit for OpenStack services.
  template: src=nofile-limits.conf.j2 dest=/etc/security/limits.d/30-nofile.conf
  tags: limits

######## Configured by default
# keystone
- include: keystone.yml

# horizon
- include: horizon.yml

# glance
- include: glance.yml

######## Not configured by default
# cinder
- include: cinder.yml

# nova
- include: nova.yml

# neutron
- include: neutron.yml

# heat
- include: heat.yml
