---
# tasks file for neutron

# Prerequisites
- name: Prepare Database for neutron.
  include: database.yml
  vars:
    db_name: "{{ openstack_neutron_db_name }}"
    db_user: "{{ openstack_neutron_db_user }}"
    db_password: "{{ openstack_neutron_db_password }}"
  tags: database

- name: Create the service user for neutron.
  include: openstack/create_user_in_project.yml
  vars:
    username: neutron
    password: "{{ openstack_neutron_keystone_password }}"
    project: service
    role: admin

- name: Create the service entity for neutron.
  include: openstack/create_service.yml
  vars:
    name: neutron
    type: network
    description: OpenStack Networking

- name: Create the API endpoint for neutron.
  include: openstack/create_endpoint.yml
  vars:
    service: network
    region: RegionOne
    endpoints:
      adminurl: "{{ openstack_neutron_adminurl }}"
      internalurl: "{{ openstack_neutron_intelnalurl }}"
      publicurl: "{{ openstack_neutron_publicurl }}"

# Install and configure
- name: Install OpenStack neutron packages.
  yum: name={{ item }} state=latest
  with_items:
    - openstack-neutron
    - openstack-neutron-ml2
    - openstack-neutron-openvswitch
    - python-neutronclient

- name: Deploy neutron configuration files from templates
  template: src={{ item.src }} dest={{ item.dest }} mode=0640 owner=root group=neutron backup=yes
  with_items:
    - { src: 'neutron/neutron.conf.j2', dest: '/etc/neutron/neutron.conf' }
    - { src: 'neutron/ml2_conf.ini.j2', dest: '/etc/neutron/plugins/ml2/ml2_conf.ini' }
    #- { src: 'neutron/linuxbridge_agent.ini.j2', dest: '/etc/neutron/plugins/ml2/linuxbridge_agent.ini' }
    - { src: 'neutron/l3_agent.ini.j2', dest: '/etc/neutron/l3_agent.ini' }
    - { src: 'neutron/dhcp_agent.ini.j2', dest: '/etc/neutron/dhcp_agent.ini' }
    - { src: 'neutron/metadata_agent.ini.j2', dest: '/etc/neutron/metadata_agent.ini' }

- name: Ensure ml2 config symbolic is exists.
  file: src=/etc/neutron/plugins/ml2/ml2_conf.ini dest=/etc/neutron/plugin.ini state=link

- name: DB sync for neutron.
  shell: |
    neutron-db-manage --config-file /etc/neutron/neutron.conf \
         --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head
  become_user: neutron
  run_once: True
  notify: restart nova

- name: Restart services
  service: name={{ item }} enabled=yes state=restarted
  with_items:
    - openstack-nova-api
    - openstack-nova-scheduler
    - openstack-nova-conductor

- name: Ensure neutron service is started and enabled on boot.
  service: name={{ item }} enabled=yes state=restarted
  ignore_errors: True
  with_items:
    - neutron-server
    - openvswitch
    - neutron-openvswitch-agent
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent