---
# tasks file for nova

# Prerequisites
- name: Prepare Database for nova.
  include: database.yml
  vars:
    db_name: "{{ openstack_nova_db_name }}"
    db_user: "{{ openstack_nova_db_user }}"
    db_password: "{{ openstack_nova_db_password }}"
  tags: database

- name: "Create nova user in service"
  include: openstack/create_user_in_project.yml
  vars:
    username: nova
    password: "{{ openstack_nova_keystone_password }}"
    project: service
    role: admin

- name: Create the service entity for nova.
  include: openstack/create_service.yml
  vars:
    name: nova
    type: compute
    description: OpenStack Compute

- name: Create the API endpoint for nova.
  include: openstack/create_endpoint.yml
  vars:
    service: compute
    region: RegionOne
    endpoints:
      adminurl: "{{ openstack_nova_adminurl }}"
      internalurl: "{{ openstack_nova_intelnalurl }}"
      publicurl: "{{ openstack_nova_publicurl }}"

# Install and configure
- name: Install OpenStack nova packages.
  yum: name={{ item }} state=latest
  with_items:
    - openstack-nova-api
    - openstack-nova-cert
    - openstack-nova-conductor
    - openstack-nova-console
    - openstack-nova-novncproxy
    - openstack-nova-scheduler
    - python-novaclient

- name: Deploy nova configuration files from templates
  template: src={{ item.src }} dest={{ item.dest }} backup=yes
  with_items:
    - { src: 'nova/nova.conf.j2', dest: '/etc/nova/nova.conf' }
    - { src: 'nova/nova-api-paste.ini.j2', dest: '/etc/nova/nova-api-paste.ini'}
  notify: restart nova

- name: DB sync for nova.
  shell: nova-manage db sync
  become_user: nova
  run_once: True

- name: Give permissions to /var/log/nova/nova.log
  file: path=/var/log/nova/nova.log state=touch mode=0640 owner=nova group=apache

- name: Ensure nova service  is started and enabled on boot.
  service: name={{ item }} enabled=yes state=restarted
  with_items:
    - openstack-nova-api
    - openstack-nova-cert
    - openstack-nova-consoleauth
    - openstack-nova-scheduler
    - openstack-nova-conductor
    - openstack-nova-novncproxy
