---
# Pre deployment tasks

- name: Install yum-plugin-priorities and epel-release
  yum: name="{{ item }}" state=latest
  with_items:
    - epel-release
    - yum-plugin-priorities

- name: Install required packages
  yum: name="{{ item }}" state=latest update_cache=yes
  with_items:
    - curl
    - git
    - python-devel
    - python-pip
    - tar
    - bind-utils
    - wget
    - httpd
    - memcached
    - mod_wsgi
    - rabbitmq-server
    - iptables
    - iptables-services

- name: Install Openstack "{{ openstack_version | default(liberty) }}"  packages
  yum: name="{{ item }}" state=latest update_cache=yes
  with_items:
    - centos-release-openstack-{{ openstack_version | default(liberty) }}

- name: Install python-openstackclient
  yum: name="{{ item }}" state=latest
  with_items:
    - python-openstackclient

- name: Set Selinux in permissive mode
  shell: setenforce 0

#SELINUX
- name: Persist in the configuration file the Selinux permissive mode.
  lineinfile: >
    dest=/etc/sysconfig/selinux
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
  with_items:
    - { regexp: "^SELINUX=", line: "SELINUX=disable" }

- name: Set hostame to "{{ openstack_controller_host }}"
  shell: hostnamectl set-hostname "{{ openstack_controller_host }}"
  ignore_errors: True

- name: Add "{{ openstack_controller_host }}" to hosts file
  lineinfile: dest=/etc/ansible/roles/ansible-role-os-controller/tests/hosts_docker
              backup=True
              backrefs=True
              state=present
              regexp='(^127.0.0.1(\s+(?! {{ openstack_controller_host }})[\w=/\-\.]+)*)\s*$'
              line='\1 {{ openstack_controller_host }}'