---
- name: 'Add "{{ role }}" role to the "{{ username }}" user to the {{ project }} project'
  command: openstack --insecure role add --project {{ project }}  --user "{{ username }}" "{{ role }}"
  run_once: True
  environment: "{{ admin_auth_env }}"