---
# - name:
#   include: service_create.yml
#   vars:
#     name:
#     type:
#     description:

- name: 'Check "{{ name }}" role exists'
  command: openstack service show "{{ name }}"
  register: serviceExist
  ignore_errors: True
  run_once: True
  environment: "{{ token_auth_env }}"

- name: 'Create service "{{ name }}"'
  shell: openstack service create --name {{ name }} --description "{{ description }}" {{ type }}
  when: serviceExist|failed
  environment: "{{ token_auth_env }}"
  run_once: True

