---
# - include: create_role.yml
#   vars:
#     project: admin
#   environment: "{{ token_auth_env }}"

- name: 'Check "{{ project }}" project exists'
  command: openstack --insecure project show "{{ project }}"
  register: projectExist
  ignore_errors: True
  run_once: True
  environment: "{{ admin_auth_env }}"

- name: 'Create the "{{ project }}" project'
  command: openstack --insecure project create --domain default --description "{{ description }}" "{{ project }}"
  when: projectExist|failed
  run_once: True
  environment: "{{ admin_auth_env }}"
